// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seed_GenreModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seed_GenreModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201805230918048_Seed_GenreModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
